lojaGames_3bi/loja_de_games/loja_de_games/Controllers/FuncionarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using loja_de_games.Models;
using loja_de_games.Repositorio;
using System.Collections.ObjectModel;

namespace loja_de_games.Controllers
{
    public class FuncionarioController : Controller
    {
        // GET: Funcionario
        public ActionResult Funcionario()
        {
            Funcionario funcionario = new Funcionario();
            return View(funcionario);
        }
        Acoes ac = new Acoes();
        [HttpPost]

        public ActionResult CadFuncionario(Funcionario fun)
        {
            ac.CadastrarFuncionario(fun);
            return View(fun);
        }

        public ActionResult ListarFuncionario()
        {
            var ExibirFunc = new Acoes();
            var TodosFunc = ExibirFunc.ListarFuncionario();
            return View(TodosFunc);
        }
    }
}

lojaGames_3bi/loja_de_games/loja_de_games/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Meu Aplicativo ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Loja de games do Guilhermino", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Início", "Index", "Home")</li>
                    <li>@Html.ActionLink("Jogo", "Jogo", "Jogo")</li>
                    <li>@Html.ActionLink("Funcionário", "Funcionario", "Funcionario")</li>
                    <li>@Html.ActionLink("Cliente", "Cliente", "Cliente")</li>
                    <li>@Html.ActionLink("Listar Funcionário", "ListarFuncionario", "Funcionario")</li>
                    <li>@Html.ActionLink("Listar Cliente", "ResultadoCliente", "Cliente")</li>
                    <li>@Html.ActionLink("Listar Jogo", "ResultadoJogo", "Jogo")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Lojinha do Guilherminooooooooooooo</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>