lojaGames_3bi/loja_de_games/loja_de_games/Models/Jogo.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace loja_de_games.Models
{
    public class Jogo
    {
        [Display(Name = "Código do jogo")]
        [Required(ErrorMessage = "preenchimento do campo obrigatório")]
        public string CodigoJogo { get; set; }

        [Display(Name = "Nome")]
        [Required(ErrorMessage = "preenchimento do campo obrigatório")]
        public string NomeJogo { get; set; }

        [Display(Name = "Versão")]
        [Required(ErrorMessage = "preenchimento do campo obrigatório")]
        public string Versao { get; set; }

        [Display(Name = "Desenvolvedor do jogo")]
        [Required(ErrorMessage = "preenchimento do campo obrigatório")]
        public string Desenvolvedor { get; set; }

        [Display(Name = "Gênero do jogo")]
        [Required(ErrorMessage = "preenchimento do campo obrigatório")]
        public string Genero { get; set; }

        [Display(Name = "Faixa etária")]
        [Required(ErrorMessage = "preenchimento do campo obrigatório")]
        public string FaixaEtaria { get; set; }

        [Display(Name = "Plataforma do jogo")]
        [Required(ErrorMessage = "preenchimento do campo obrigatório")]
        public string Plataforma { get; set; }

        [Display(Name = "Sinopse do jogo")]
        [Required(ErrorMessage = "preenchimento do campo obrigatório")]
        public string Sinopse { get; set; }

        [Display(Name = "Ano de lançamento")]
        [Required(ErrorMessage = "preenchimento do campo obrigatório")]
        public string AnoLancamento { get; set; }
    }
}

lojaGames_3bi/loja_de_games/loja_de_games/Controllers/JogoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using loja_de_games.Models;
using loja_de_games.Repositorio;
using System.Collections.ObjectModel;

namespace loja_de_games.Controllers
{
    public class JogoController : Controller
    {
        // GET: Jogo
        public ActionResult Jogo()
        {
            Jogo jogo = new Jogo();
            return View(jogo);
        }
        AcoesJogo ac = new AcoesJogo();
        [HttpPost]

        public ActionResult CadJogo(Jogo jogo)
        {
            ac.CadastrarJogo(jogo);
            return View(jogo);
        }

        public ActionResult ResultadoJogo()
        {
            var ExibirJogo = new AcoesJogo();
            var TodosJogos = ExibirJogo.ResultadoJogo();
            return View(TodosJogos);
        }

    }
}

lojaGames_3bi/loja_de_games/loja_de_games/Views/Jogo/CadJogo.cshtml
@model loja_de_games.Models.Jogo
@{
    ViewBag.Title = "CadJogo";
}

<h2>Dados Cadastrados com Sucesso</h2>
<br />
<p>@Html.ActionLink("Voltar", "Jogo")</p>
<p>@Html.ActionLink("Vizualizar Jogo", "ResultadoJogo")</p>

lojaGames_3bi/loja_de_games/loja_de_games/Views/Jogo/IndexJogo.cshtml
@model loja_de_games.Models.Jogo


@{
    ViewBag.Title = "IndexJogo";
}

<h1>Cadastro de Jogos</h1>
@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
<fildset>

    <div class="editor-label">
        @Html.LabelFor(model => model.CodigoJogo)
    </div>
    <div class="editor-field">
        @Html.EditorFor(model => model.CodigoJogo)
        @Html.ValidationMessageFor(model => model.CodigoJogo)
    </div>

    <div class="editor-label"> 
        @Html.LabelFor(model => model.NomeJogo)
    </div>
    <div class="editor-field">
        @Html.EditorFor(model => model.NomeJogo)
        @Html.ValidationMessageFor(model => model.NomeJogo)
    </div>

    <div class="editor-label">
        @Html.LabelFor(model => model.Versao)
    </div>
    <div class="editor-field">
        @Html.EditorFor(model => model.Versao)
        @Html.ValidationMessageFor(model => model.Versao)
    </div>

    <div class="editor-label">
        @Html.LabelFor(model => model.Desenvolvedor)
    </div>
    <div class="editor-field">
        @Html.EditorFor(model => model.Desenvolvedor)
        @Html.ValidationMessageFor(model => model.Desenvolvedor)
    </div>

    <div class="editor-label">Gênero
    <div class="editor-label">
        @Html.LabelFor(model => model.Genero)
    </div>
    <div class="editor-field">
        @Html.EditorFor(model => model.Genero)
        @Html.ValidationMessageFor(model => model.Genero)
    </div>

    <div class="editor-label">
        @Html.LabelFor(model => model.FaixaEtaria)
    </div>
    <div class="editor-field">
        @Html.EditorFor(model => model.FaixaEtaria)
        @Html.ValidationMessageFor(model => model.FaixaEtaria)
    </div>

    <div class="editor-label">
        @Html.LabelFor(model => model.Plataforma)
    </div>
    <div class="editor-field">
        @Html.EditorFor(model => model.Plataforma)
        @Html.ValidationMessageFor(model => model.Plataforma)
    </div>

    <div class="editor-label">
        @Html.LabelFor(model => model.AnoLancamento)
    </div>
    <div class="editor-field">
        @Html.EditorFor(model => model.AnoLancamento)
        @Html.ValidationMessageFor(model => model.AnoLancamento)
    </div>

    <div class="editor-label">
        @Html.LabelFor(model => model.Sinopse)
    </div>
    <div class="editor-field">
        @Html.EditorFor(model => model.Sinopse)
        @Html.ValidationMessageFor(model => model.Sinopse)
    </div>

    <p><input type="submit" value="Cadastrar" /></p>
</fildset>

    @section Scripts{
            @Scripts.Render("~/bundles/jqueryval");
        }
}

lojaGames_3bi/loja_de_games/loja_de_games/Views/Jogo/Jogo.cshtml
@model loja_de_games.Models.Jogo


@{
    ViewBag.Title = "IndexJogo";
}

<h1>Cadastro de Jogos</h1>
@using (Html.BeginForm("CadJogo", "Jogo", FormMethod.Post))
{
    @Html.ValidationSummary(true)
    <fildset>

        <div class="editor-label">
            @Html.LabelFor(model => model.CodigoJogo)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.CodigoJogo)
            @Html.ValidationMessageFor(model => model.CodigoJogo)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.NomeJogo)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.NomeJogo)
            @Html.ValidationMessageFor(model => model.NomeJogo)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Versao)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Versao)
            @Html.ValidationMessageFor(model => model.Versao)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Desenvolvedor)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Desenvolvedor)
            @Html.ValidationMessageFor(model => model.Desenvolvedor)
        </div>

        <div class="editor-label">
            Gênero
            <div class="editor-label">
                @Html.LabelFor(model => model.Genero)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Genero)
                @Html.ValidationMessageFor(model => model.Genero)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.FaixaEtaria)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.FaixaEtaria)
                @Html.ValidationMessageFor(model => model.FaixaEtaria)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.Plataforma)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Plataforma)
                @Html.ValidationMessageFor(model => model.Plataforma)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.AnoLancamento)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.AnoLancamento)
                @Html.ValidationMessageFor(model => model.AnoLancamento)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.Sinopse)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Sinopse)
                @Html.ValidationMessageFor(model => model.Sinopse)
            </div>

            <p><input type="submit" value="Cadastrar" /></p>
    </fildset>

    @section Scripts{
        @Scripts.Render("~/bundles/jqueryval");
    }
}

lojaGames_3bi/loja_de_games/loja_de_games/Views/Jogo/ResultadoJogo.cshtml
@model IEnumerable<loja_de_games.Models.Jogo>

@{
    ViewBag.Title = "ResultadoJogo";
}

<p>@Html.ActionLink("Cadastrar Jogo", "Jogo")</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CodigoJogo)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.NomeJogo)
        </th>

        <th>

            @Html.DisplayNameFor(model => model.Versao)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.Desenvolvedor)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.Genero)
        </th>

        <th>
            >
            @Html.DisplayNameFor(model => model.FaixaEtaria)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.Plataforma)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.Sinopse)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.AnoLancamento)
        </th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.CodigoJogo)
    </td>

    <td>
        @Html.DisplayFor(modelItem => item.NomeJogo)
    </td>

    <td>
        @Html.DisplayFor(modelItem => item.Versao)
    </td>

    <td>
        @Html.DisplayFor(modelItem => item.Desenvolvedor)
    </td>

    <td>
        @Html.DisplayFor(modelItem => item.Genero)
    </td>

    <td>
        @Html.DisplayFor(modelItem => item.FaixaEtaria)
    </td>

    <td>
        @Html.DisplayFor(modelItem => item.Plataforma)
    </td>

    <td>
        @Html.DisplayFor(modelItem => item.Sinopse)
    </td>

    <td>
        @Html.DisplayFor(modelItem => item.AnoLancamento)
    </td>
    <td>
        @Html.ActionLink("Alterar", "AltJogo", null, new { cdJogo = item.CodigoJogo }, new { @class = "bnt btn-primary btn-xs" })
        @Html.ActionLink("Deletar", "DelJogo", null, new { cdJogo = item.CodigoJogo }, new { @class = "bnt btn-danger btn-xs" })
    </td>
</tr>
    }
</table>